### ISSUE TITLE
Updated Splash Video

### ISSUE THREAD

**Issue by alexdaniel654** [nottinghamtec/Main-Website#63]
I'm in the process of updating the dynamic slideshow video I made a few years ago with some new pictures and timelapses etc.

Given its ended up being used here as well as a 16:9 1080p monitor, if you give me a size, I'll make a version that's optimised to the website (doesn't have as many labels/logos and doesn't FTB at the end etc). I can also render it out at a lower bit rate so you don't have to reduce resolution and end up with the potato quality video your'e using at the moment.

**Comment by harry-bridge** [comment]
Ooh lovely, 1920x1080 will work well as it gets scaled to the display when it's loaded, I can't remember if the current one has audio but if this one could be without audio as well that would be awesome. From my reading online it seems to be that 4000kbps is the recommended starting bit rate for a 1920x1080 web video

**Comment by alexdaniel654** [comment]
h.264 I assume?

**Comment by davidtaylorhq** [comment]
@alexdaniel654 Yeah, h264 would be perfect :)

**Comment by alexdaniel654** [comment]
One 4Mbps H.264 1920x1080 dynamic slideshow thingy. [https://coherencetechnical.co.uk/owncloud/index.php/s/O3rBDo3nfLDk80p](url)

**Comment by davidtaylorhq** [comment]
That looks great :)

Not sure where @pickleshb got the 4Mbps figure from, but IMO 270mb is way too much for people to be downloading to view our homepage. The current video is 80mb, so if we can get closer to that then it would be preferable.

I just ran the new video through handbrake with an average bitrate of 700kbps and it didn't look bad - file was 48mb. Obviously would be better if @alexdaniel654 can export it at the lower bitrate rather than recompressing. Can we try getting the file size down to something around 50mb?

**Comment by alexdaniel654** [comment]
Cause, stand by.

**Comment by davidtaylorhq** [comment]
If the compression makes it look utterly awful, the alternative is reducing the length of it

**Comment by alexdaniel654** [comment]
Slightly more mashed potato version with some bits cut out. https://coherencetechnical.co.uk/owncloud/index.php/s/OheYraCZ7SxW08M

**Comment by davidtaylorhq** [comment]
Tried hosting this on smugmug... but smugmug recompressed it to be twice it's original size... *facepalm*

Now hosted on static.nottinghamtec.co.uk, which is an CNAME to an S3 bucket, with cloudflare caching enabled. Seems much quicker than before, and looks less potato quality.

Thanks @alexdaniel654 :)
